# Copyright (c) 2026 Pietro Chierico
# SPDX-License-Identifier: MIT

"""
Script 2 - PPG Dataset Analysis, Training, Testing, and Model Export

Purpose
-------
Load the WiFi IR CSV generated by Script 1, visualize boxplots for every feature grouped
by target, choose feature combinations, train a simple AI model, test it, and
export the model for live classification.

Install
-------
pip install numpy pandas scipy matplotlib scikit-learn joblib PyQt6

Run
---
python script2_analysis_training_export.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QApplication, QFileDialog, QGridLayout, QHBoxLayout, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QMessageBox, QPushButton, QTextEdit,
    QVBoxLayout, QWidget, QComboBox, QDoubleSpinBox
)
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from ppg_feature_utils import FEATURE_COLUMNS

APPLE_STYLE = """
QMainWindow, QWidget { background-color: #0b0f17; color: #f5f7fb; font-family: -apple-system, BlinkMacSystemFont, Segoe UI; }
QLabel { color: #f5f7fb; font-size: 14px; }
QPushButton { background-color: rgba(255,255,255,0.10); border: 1px solid rgba(255,255,255,0.18); border-radius: 14px; padding: 10px 16px; color: #f5f7fb; font-weight: 600; }
QPushButton:hover { background-color: rgba(255,255,255,0.18); }
QComboBox, QDoubleSpinBox, QListWidget, QTextEdit { background-color: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.20); border-radius: 12px; padding: 7px; color: #f5f7fb; }
"""


class AnalysisTrainingWindow(QMainWindow):
    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("PPG Feature Analysis and AI Training")
        self.resize(1350, 900)
        self.df: pd.DataFrame | None = None
        self.trained_pipeline: Pipeline | None = None
        self.selected_features: list[str] = []
        self.report_text = ""
        self._build_ui()

    def _build_ui(self) -> None:
        central = QWidget()
        root = QVBoxLayout(central)

        title = QLabel("PPG IR Resting vs Walking - Analysis, Training, Export")
        title.setStyleSheet("font-size: 30px; font-weight: 800;")
        root.addWidget(title)

        controls = QHBoxLayout()
        self.load_button = QPushButton("Load Dataset CSV")
        self.plot_button = QPushButton("Show Boxplots")
        self.train_button = QPushButton("Train / Test Model")
        self.export_button = QPushButton("Export Model")
        for button in [self.load_button, self.plot_button, self.train_button, self.export_button]:
            controls.addWidget(button)
        root.addLayout(controls)

        settings = QGridLayout()
        self.model_combo = QComboBox()
        self.model_combo.addItems(["Logistic Regression", "SVM RBF", "Random Forest"])
        self.test_size_spin = QDoubleSpinBox()
        self.test_size_spin.setRange(0.10, 0.50)
        self.test_size_spin.setSingleStep(0.05)
        self.test_size_spin.setValue(0.25)
        self.test_size_spin.setDecimals(2)
        settings.addWidget(QLabel("Model"), 0, 0)
        settings.addWidget(self.model_combo, 0, 1)
        settings.addWidget(QLabel("Test size"), 0, 2)
        settings.addWidget(self.test_size_spin, 0, 3)
        root.addLayout(settings)

        body = QHBoxLayout()
        left = QVBoxLayout()
        self.info_label = QLabel("No dataset loaded")
        self.info_label.setStyleSheet("background-color: rgba(255,255,255,0.07); border-radius: 18px; padding: 16px;")
        self.feature_list = QListWidget()
        self.feature_list.setSelectionMode(QListWidget.SelectionMode.MultiSelection)
        left.addWidget(self.info_label)
        left.addWidget(QLabel("Select feature combination"))
        left.addWidget(self.feature_list)

        self.figure = Figure(figsize=(8, 6))
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setStyleSheet("background-color: #0b0f17;")

        right = QVBoxLayout()
        self.output = QTextEdit()
        self.output.setReadOnly(True)
        right.addWidget(self.canvas, stretch=3)
        right.addWidget(self.output, stretch=2)

        body.addLayout(left, stretch=1)
        body.addLayout(right, stretch=4)
        root.addLayout(body)
        self.setCentralWidget(central)

        self.load_button.clicked.connect(self.load_csv)
        self.plot_button.clicked.connect(self.show_boxplots)
        self.train_button.clicked.connect(self.train_model)
        self.export_button.clicked.connect(self.export_model)

    def load_csv(self) -> None:
        path, _ = QFileDialog.getOpenFileName(self, "Load Dataset CSV", str(Path.home()), "CSV files (*.csv)")
        if not path:
            return
        try:
            df = pd.read_csv(path)
            missing = [c for c in ["target", *FEATURE_COLUMNS] if c not in df.columns]
            if missing:
                raise ValueError(f"Missing required columns: {missing}")
            df = df.dropna(subset=["target", *FEATURE_COLUMNS]).copy()
            df = df[df["target"].isin(["Resting", "Walking"])]
            if df["target"].nunique() < 2:
                raise ValueError("The dataset must contain both Resting and Walking rows.")
            self.df = df
            self.populate_feature_list()
            counts = df["target"].value_counts().to_dict()
            self.info_label.setText(f"Loaded: {Path(path).name}\nRows: {len(df)}\nClass counts: {counts}")
            self.output.setText("Dataset loaded. Select features, show boxplots, then train a model.")
            self.show_boxplots()
        except Exception as exc:
            QMessageBox.critical(self, "Load error", f"Could not load dataset:\n{exc}")

    def populate_feature_list(self) -> None:
        self.feature_list.clear()
        for feature in FEATURE_COLUMNS:
            item = QListWidgetItem(feature)
            item.setCheckState(Qt.CheckState.Checked)
            self.feature_list.addItem(item)

    def get_selected_features(self) -> list[str]:
        features = []
        for i in range(self.feature_list.count()):
            item = self.feature_list.item(i)
            if item.checkState() == Qt.CheckState.Checked:
                features.append(item.text())
        return features

    def show_boxplots(self) -> None:
        if self.df is None:
            QMessageBox.information(self, "No dataset", "Load a dataset CSV first.")
            return
        features = self.get_selected_features() or FEATURE_COLUMNS
        max_features = min(len(features), 12)
        features = features[:max_features]

        self.figure.clear()
        rows = int(np.ceil(max_features / 3))
        axes = self.figure.subplots(rows, 3)
        axes = np.array(axes).reshape(-1)
        for ax, feature in zip(axes, features):
            data = [
                self.df[self.df["target"] == "Resting"][feature].values,
                self.df[self.df["target"] == "Walking"][feature].values,
            ]
            ax.boxplot(data, labels=["Resting", "Walking"])
            ax.set_title(feature, fontsize=9)
            ax.tick_params(axis="x", labelrotation=20)
        for ax in axes[len(features):]:
            ax.axis("off")
        self.figure.tight_layout()
        self.canvas.draw()

    def build_model(self):
        name = self.model_combo.currentText()
        if name == "Logistic Regression":
            return Pipeline([("scaler", StandardScaler()), ("model", LogisticRegression(max_iter=2000))])
        if name == "SVM RBF":
            return Pipeline([("scaler", StandardScaler()), ("model", SVC(kernel="rbf", probability=True))])
        return Pipeline([("model", RandomForestClassifier(n_estimators=200, random_state=42, class_weight="balanced"))])

    def train_model(self) -> None:
        if self.df is None:
            QMessageBox.information(self, "No dataset", "Load a dataset CSV first.")
            return
        features = self.get_selected_features()
        if not features:
            QMessageBox.information(self, "No features", "Select at least one feature.")
            return
        try:
            X = self.df[features].values
            y = self.df["target"].values
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=float(self.test_size_spin.value()), random_state=42, stratify=y
            )
            pipeline = self.build_model()
            pipeline.fit(X_train, y_train)
            y_pred = pipeline.predict(X_test)
            acc = accuracy_score(y_test, y_pred)
            cm = confusion_matrix(y_test, y_pred, labels=["Resting", "Walking"])
            report = classification_report(y_test, y_pred, labels=["Resting", "Walking"], zero_division=0)
            self.trained_pipeline = pipeline
            self.selected_features = features

            self.report_text = (
                f"Model: {self.model_combo.currentText()}\n"
                f"Selected features: {features}\n"
                f"Rows: {len(self.df)} | Train: {len(X_train)} | Test: {len(X_test)}\n"
                f"Accuracy: {acc:.3f}\n\n"
                f"Confusion matrix, rows=true, columns=predicted\n"
                f"Labels: Resting, Walking\n{cm}\n\n"
                f"Classification report:\n{report}"
            )
            self.output.setText(self.report_text)
        except Exception as exc:
            QMessageBox.critical(self, "Training error", f"Could not train model:\n{exc}")

    def export_model(self) -> None:
        if self.trained_pipeline is None:
            QMessageBox.information(self, "No trained model", "Train a model before exporting.")
            return
        default_name = f"ppg_resting_walking_model_{int(time.time())}.joblib"
        path, _ = QFileDialog.getSaveFileName(self, "Export Model", str(Path.home() / default_name), "Joblib files (*.joblib)")
        if not path:
            return
        try:
            package = {
                "pipeline": self.trained_pipeline,
                "feature_names": self.selected_features,
                "target_names": ["Resting", "Walking"],
                "created_at_s": time.time(),
                "report": self.report_text,
            }
            joblib.dump(package, path)
            meta_path = str(Path(path).with_suffix(".json"))
            with open(meta_path, "w", encoding="utf-8") as f:
                json.dump({k: v for k, v in package.items() if k != "pipeline"}, f, indent=2)
            self.output.append(f"\nExported model to:\n{path}\nMetadata:\n{meta_path}")
        except Exception as exc:
            QMessageBox.critical(self, "Export error", f"Could not export model:\n{exc}")


def main() -> None:
    app = QApplication(sys.argv)
    app.setStyleSheet(APPLE_STYLE)
    win = AnalysisTrainingWindow()
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
