# Copyright (c) 2026 Pietro Chierico
# SPDX-License-Identifier: MIT

"""
Script 2 - Caffeine Intake PPG Feature Analysis

Purpose
-------
Open the big CSV generated by Script 1, analyze how PPG-derived features change
from baseline over time, and export summary CSV files and Apple-style plots.

Install
-------
pip install numpy pandas matplotlib PyQt6

Run
---
python script2_caffeine_analysis_export.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QApplication, QFileDialog, QGridLayout, QHBoxLayout, QLabel, QMainWindow,
    QMessageBox, QPushButton, QTableWidget, QTableWidgetItem, QTextEdit,
    QVBoxLayout, QWidget
)

BASE_DIR = Path(__file__).parent.resolve()
DEFAULT_CSV = BASE_DIR / "caffeine_ppg_big_dataset.csv"
RESULTS_DIR = BASE_DIR / "caffeine_analysis_results"

FEATURES = [
    "bpm", "dominant_bpm", "rmssd_ms", "sdnn_ms", "ppg_amplitude",
    "signal_power", "noise_power", "snr_db", "perfusion_index_proxy",
    "motion_artifact_proxy"
]

APPLE_STYLE = """
QMainWindow, QWidget {
    background-color: #0b0f17;
    color: #f5f7fb;
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI;
}
QLabel { color: #f5f7fb; font-size: 14px; }
QPushButton {
    background-color: rgba(255,255,255,0.10);
    border: 1px solid rgba(255,255,255,0.18);
    border-radius: 14px;
    padding: 10px 16px;
    color: #f5f7fb;
    font-weight: 700;
}
QPushButton:hover { background-color: rgba(255,255,255,0.18); }
QPushButton#primaryButton {
    background-color: #0071e3;
    border: 1px solid #3f9bff;
}
QTextEdit, QTableWidget {
    background-color: rgba(255,255,255,0.07);
    border: 1px solid rgba(255,255,255,0.15);
    border-radius: 18px;
    color: #f5f7fb;
    gridline-color: rgba(255,255,255,0.12);
}
QHeaderView::section {
    background-color: rgba(255,255,255,0.12);
    color: white;
    border: 0px;
    padding: 8px;
}
"""


def available_features(df: pd.DataFrame) -> list[str]:
    return [feature for feature in FEATURES if feature in df.columns]


def summarize_by_subject_time(df: pd.DataFrame, features: list[str]) -> pd.DataFrame:
    return df.groupby(["subject_id", "minutes_after_coffee"], as_index=False)[features].mean()


def compute_baseline_changes(summary: pd.DataFrame, features: list[str]) -> pd.DataFrame:
    rows = []
    for subject_id, sub in summary.groupby("subject_id"):
        sub = sub.sort_values("minutes_after_coffee")
        baseline = sub[sub["minutes_after_coffee"] == 0]
        if baseline.empty:
            continue
        base = baseline.iloc[0]
        for _, row in sub.iterrows():
            out = {"subject_id": subject_id, "minutes_after_coffee": row["minutes_after_coffee"]}
            for feature in features:
                base_value = base[feature]
                value = row[feature]
                out[f"{feature}_value"] = value
                out[f"{feature}_delta"] = value - base_value
                out[f"{feature}_percent_change"] = ((value - base_value) / abs(base_value) * 100) if base_value != 0 else np.nan
            rows.append(out)
    return pd.DataFrame(rows)


def make_plots(summary: pd.DataFrame, changes: pd.DataFrame, features: list[str], output_dir: Path) -> None:
    output_dir.mkdir(exist_ok=True)
    plt.rcParams.update({
        "figure.facecolor": "#0b0f17",
        "axes.facecolor": "#0b0f17",
        "axes.edgecolor": "#5b6575",
        "axes.labelcolor": "#f5f7fb",
        "xtick.color": "#f5f7fb",
        "ytick.color": "#f5f7fb",
        "text.color": "#f5f7fb",
        "grid.color": "#334155",
        "legend.facecolor": "#111827",
        "legend.edgecolor": "#334155",
    })

    for feature in features:
        plt.figure(figsize=(11, 6))
        for subject_id, sub in summary.groupby("subject_id"):
            sub = sub.sort_values("minutes_after_coffee")
            plt.plot(sub["minutes_after_coffee"], sub[feature], marker="o", linewidth=2, label=str(subject_id))
        plt.title(f"{feature} over time after caffeine intake")
        plt.xlabel("Minutes after coffee")
        plt.ylabel(feature)
        plt.grid(True, alpha=0.35)
        plt.legend()
        plt.tight_layout()
        plt.savefig(output_dir / f"{feature}_subjects_over_time.png", dpi=180)
        plt.close()

        percent_col = f"{feature}_percent_change"
        if percent_col in changes.columns:
            plt.figure(figsize=(11, 6))
            for subject_id, sub in changes.groupby("subject_id"):
                sub = sub.sort_values("minutes_after_coffee")
                plt.plot(sub["minutes_after_coffee"], sub[percent_col], marker="o", linewidth=2, label=str(subject_id))
            plt.axhline(0, linewidth=1)
            plt.title(f"{feature} percent change from baseline")
            plt.xlabel("Minutes after coffee")
            plt.ylabel("Percent change from baseline (%)")
            plt.grid(True, alpha=0.35)
            plt.legend()
            plt.tight_layout()
            plt.savefig(output_dir / f"{feature}_percent_change.png", dpi=180)
            plt.close()


class AnalysisWindow(QMainWindow):
    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("Caffeine Intake PPG Analysis")
        self.resize(1200, 820)
        self.df: pd.DataFrame | None = None
        self.summary: pd.DataFrame | None = None
        self.changes: pd.DataFrame | None = None
        self.csv_path: Path | None = None
        self._build_ui()

    def _card(self, text: str) -> QLabel:
        label = QLabel(text)
        label.setStyleSheet("background-color: rgba(255,255,255,0.07); border-radius: 18px; padding: 16px;")
        return label

    def _build_ui(self) -> None:
        central = QWidget()
        layout = QVBoxLayout(central)
        layout.setSpacing(16)

        title = QLabel("Caffeine Intake Project · Feature Analysis")
        title.setStyleSheet("font-size: 32px; font-weight: 900; letter-spacing: -1px;")
        subtitle = QLabel("Load the big CSV, compute baseline changes, compare subjects, and export summary tables and plots.")
        subtitle.setStyleSheet("font-size: 15px; color: #a9b4c7;")

        buttons = QHBoxLayout()
        self.load_button = QPushButton("Load Big CSV")
        self.load_button.setObjectName("primaryButton")
        self.analyze_button = QPushButton("Run Analysis")
        self.export_button = QPushButton("Export Results")
        for button in [self.load_button, self.analyze_button, self.export_button]:
            buttons.addWidget(button)

        cards = QHBoxLayout()
        self.file_label = self._card("File: Not loaded")
        self.subjects_label = self._card("Subjects: --")
        self.rows_label = self._card("Rows: --")
        self.features_label = self._card("Features: --")
        for card in [self.file_label, self.subjects_label, self.rows_label, self.features_label]:
            cards.addWidget(card)

        self.report = QTextEdit()
        self.report.setReadOnly(True)
        self.report.setPlaceholderText("Analysis report will appear here.")
        self.table = QTableWidget()

        layout.addWidget(title)
        layout.addWidget(subtitle)
        layout.addLayout(buttons)
        layout.addLayout(cards)
        layout.addWidget(self.report, 2)
        layout.addWidget(self.table, 3)
        self.setCentralWidget(central)

        self.load_button.clicked.connect(self.load_csv)
        self.analyze_button.clicked.connect(self.run_analysis)
        self.export_button.clicked.connect(self.export_results)

    def load_csv(self) -> None:
        path, _ = QFileDialog.getOpenFileName(self, "Open Caffeine PPG Big CSV", str(DEFAULT_CSV), "CSV files (*.csv)")
        if not path:
            return
        try:
            self.df = pd.read_csv(path)
            self.csv_path = Path(path)
            required = {"subject_id", "minutes_after_coffee"}
            missing = required - set(self.df.columns)
            if missing:
                raise ValueError(f"Missing required columns: {', '.join(sorted(missing))}")
            features = available_features(self.df)
            if not features:
                raise ValueError("No recognized PPG feature columns found.")
            self.file_label.setText(f"File: {self.csv_path.name}")
            self.subjects_label.setText(f"Subjects: {self.df['subject_id'].nunique()}")
            self.rows_label.setText(f"Rows: {len(self.df)}")
            self.features_label.setText(f"Features: {len(features)}")
            self.report.setText("CSV loaded successfully. Click Run Analysis.")
        except Exception as exc:
            QMessageBox.critical(self, "Load Error", str(exc))

    def run_analysis(self) -> None:
        if self.df is None:
            QMessageBox.information(self, "No CSV", "Load a CSV first.")
            return
        try:
            features = available_features(self.df)
            self.summary = summarize_by_subject_time(self.df, features)
            self.changes = compute_baseline_changes(self.summary, features)
            self.populate_table(self.summary)

            n_subjects = self.df["subject_id"].nunique()
            timepoints = sorted(self.df["minutes_after_coffee"].dropna().unique().tolist())
            missing_baseline = []
            for subject_id, sub in self.df.groupby("subject_id"):
                if 0 not in set(sub["minutes_after_coffee"]):
                    missing_baseline.append(str(subject_id))

            strongest_lines = []
            for feature in features:
                percent_col = f"{feature}_percent_change"
                if percent_col in self.changes.columns and not self.changes.empty:
                    temp = self.changes[self.changes["minutes_after_coffee"] > 0].copy()
                    if not temp.empty:
                        idx = temp[percent_col].abs().idxmax()
                        row = temp.loc[idx]
                        strongest_lines.append(
                            f"• {feature}: strongest change in subject {row['subject_id']} at {row['minutes_after_coffee']} min ({row[percent_col]:.2f}%)."
                        )

            report = [
                "ANALYSIS SUMMARY",
                "",
                f"Loaded file: {self.csv_path}",
                f"Subjects: {n_subjects}",
                f"Time points: {timepoints}",
                f"Feature columns: {', '.join(features)}",
                "",
            ]
            if missing_baseline:
                report.append("WARNING: These subjects have no baseline and cannot be used for baseline-change analysis:")
                report.append(", ".join(missing_baseline))
                report.append("")
            report.append("Strongest observed percent changes:")
            report.extend(strongest_lines[:10] if strongest_lines else ["No baseline-change rows available yet."])
            self.report.setText("\n".join(report))
        except Exception as exc:
            QMessageBox.critical(self, "Analysis Error", str(exc))

    def populate_table(self, df: pd.DataFrame) -> None:
        preview = df.round(3).copy()
        self.table.setRowCount(len(preview))
        self.table.setColumnCount(len(preview.columns))
        self.table.setHorizontalHeaderLabels([str(c) for c in preview.columns])
        for r in range(len(preview)):
            for c, col in enumerate(preview.columns):
                item = QTableWidgetItem(str(preview.iloc[r, c]))
                item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
                self.table.setItem(r, c, item)
        self.table.resizeColumnsToContents()

    def export_results(self) -> None:
        if self.summary is None or self.changes is None or self.df is None:
            QMessageBox.information(self, "No Analysis", "Run the analysis first.")
            return
        folder = QFileDialog.getExistingDirectory(self, "Choose Export Folder", str(RESULTS_DIR))
        if not folder:
            return
        try:
            output_dir = Path(folder)
            output_dir.mkdir(exist_ok=True)
            features = available_features(self.df)
            self.summary.to_csv(output_dir / "caffeine_subject_time_summary.csv", index=False)
            self.changes.to_csv(output_dir / "caffeine_baseline_changes.csv", index=False)
            make_plots(self.summary, self.changes, features, output_dir)
            QMessageBox.information(self, "Export Complete", f"Results exported to:\n{output_dir}")
        except Exception as exc:
            QMessageBox.critical(self, "Export Error", str(exc))


def main() -> None:
    app = QApplication(sys.argv)
    app.setStyleSheet(APPLE_STYLE)
    win = AnalysisWindow()
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
